
  name: lizard
  version: '0.1'
  summary: Managing your own Linux server has never been easier. # 79 char long summary
  description: |
    Lizard is a simple CLI application for managing your Linux Server. 
    Install the server stack and configure your instance in the cloud 
    of Google Cloud Platform, Amazon Web Services, DigitalOcean or any 
    of your preference.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
